import {
  TaxonomyVariant,
  GoogleReviewItem,
  WorkflowMilestone,
  BeforeAfterItem,
} from './types';
import { getAssetUrl } from './assetHelper';

// Curated Architectural Imagery (Warm Alabaster, Cream, Fluted Oak & Travertine)
export const ASSET_LIBRARY = {
  hero: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=2000&q=85', // Expansive warm alabaster living room
  heroAi: getAssetUrl('/images/hero_luxury_bg.jpg'),
  beforeConstruction: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1600&q=80', // Raw unrenovated concrete site
  beforeConstructionLocal: getAssetUrl('/images/before_construction_shell.jpg'),
  afterFinished: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=85', // Completed luxury warm-toned living room
  afterFinishedAi: getAssetUrl('/images/hero_luxury_bg.jpg'),
  handoverGift: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1200&q=80', // Elegant interior handover aesthetic
  handoverGiftAi: getAssetUrl('/images/luxury_handover_keys.jpg'),
  kitchenLShaped: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1200&q=80',
  kitchenUShaped: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=1200&q=80',
  kitchenIsland: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
  kitchenIslandAi: getAssetUrl('/images/luxury_kitchen_island.jpg'),
  kitchenParallel: 'https://images.unsplash.com/photo-1556909212-d5b604d0c90d?auto=format&fit=crop&w=1200&q=80',
  bedroomJapandi: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1200&q=80',
  bedroomMasterAi: getAssetUrl('/images/luxury_master_suite.jpg'),
  bedroomClassical: 'https://images.unsplash.com/photo-1540518614846-7ede433c4ef0?auto=format&fit=crop&w=1200&q=80',
  bedroomSmartPod: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1200&q=80',
  livingAcoustic: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80',
  livingLoungeAi: getAssetUrl('/images/architectural_marble_lounge.jpg'),
  livingTravertine: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1200&q=80',
  commercialSuite: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
  commercialRetail: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80',
  materialsMoodboardAi: getAssetUrl('/images/materials_moodboard.jpg'),
  materialTravertine: getAssetUrl('/images/material_travertine.jpg'),
  materialSmokedOak: getAssetUrl('/images/material_smoked_oak.jpg'),
  materialCalacatta: getAssetUrl('/images/material_calacatta.jpg'),
  materialPurEdge: getAssetUrl('/images/material_pur_edge.jpg'),
  materialChampagneBrass: getAssetUrl('/images/material_champagne_brass.jpg'),
  blueprintScanAi: getAssetUrl('/images/architectural_blueprint_scan.jpg'),
  factoryCncAi: getAssetUrl('/images/german_factory_cnc.jpg'),
  draftingDetailAi: getAssetUrl('/images/architect_drawing_detail.jpg'),
  clientPriya: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
  clientCouple: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80',
  clientVikram: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
};

// 1. Service Taxonomy Catalog
export const TAXONOMY_VARIANTS: TaxonomyVariant[] = [
  // --- KITCHENS ---
  {
    id: 'tax-k-1',
    category: 'kitchen',
    title: 'L-Shaped Efficiency Suite',
    subtitle: 'Smart Ergonomics for 2BHK & 3BHK Kitchens',
    tag: 'Best for 2BHK & 3BHK',
    image: ASSET_LIBRARY.kitchenLShaped,
    localAiImage: getAssetUrl('/images/kitchen_lshaped_luxury.jpg'),
    recommendedSize: '90 - 130 sq.ft Floorplate',
    hardwareSpec: 'Blum Tandembox / Hettich Sensys Soft-Close',
    coreMaterial: 'Action TESA BWP HDHMR (Moisture Proof)',
    edgeBanding: 'German Homag 1.3mm PUR Seamless Joint',
    finishType: 'Matte Cashmere Anti-Fingerprint Acrylic',
    startingPrice: '₹2.85 Lakh',
    features: [
      'Zero-dead-space corner carousel unit',
      'Soft-close cutlery and spice pullout drawers',
      'Stain-free Calacatta quartz countertop',
      'Concealed warm LED under-cabinet lights',
    ],
    quoteDefaults: {
      configuration: '2BHK',
      scope: 'kitchen_only',
      aesthetic: 'warm_minimalist',
      materialTier: 'premium_german',
    },
  },
  {
    id: 'tax-k-2',
    category: 'kitchen',
    title: 'U-Shaped Continuous Workspace',
    subtitle: 'Continuous Worktop & High-Capacity Storage',
    tag: 'Maximum Storage',
    image: ASSET_LIBRARY.kitchenUShaped,
    localAiImage: getAssetUrl('/images/kitchen_ushaped_luxury.jpg'),
    recommendedSize: '130 - 190 sq.ft Floorplate',
    hardwareSpec: 'Blum Servo-Drive Motorized Lift-Up Wall Units',
    coreMaterial: 'Boiling Water Proof Calibrated Marine Ply',
    edgeBanding: 'Zero-Joint Laser Edge Bonding',
    finishType: 'Warm Ivory Satin PU Lacquer',
    startingPrice: '₹3.90 Lakh',
    features: [
      'Triangular layout: Cooktop, Sink & Fridge in easy reach',
      'Full-height pantry unit with 6 pullout baskets',
      'Built-in appliance garage for microwave & coffee bar',
      'Undermount quartz sink with pull-out spray faucet',
    ],
    quoteDefaults: {
      configuration: '3BHK',
      scope: 'kitchen_only',
      aesthetic: 'modern_classical',
      materialTier: 'premium_german',
    },
  },
  {
    id: 'tax-k-3',
    category: 'kitchen',
    title: 'Monolithic Travertine Island Suite',
    subtitle: 'Open-Concept Island with Breakfast Bar',
    tag: 'Villa & Penthouse Signature',
    image: ASSET_LIBRARY.kitchenIsland,
    localAiImage: ASSET_LIBRARY.kitchenIslandAi,
    recommendedSize: '200+ sq.ft Open Plan',
    hardwareSpec: 'Blum Legrabox Pure Titanium / Servo-Drive Electric',
    coreMaterial: 'Marine Ply + Solid Smoked European Ash',
    edgeBanding: '45-Degree Mitered Stone Edge & Micro PUR',
    finishType: 'Travertine Stone Waterfall + Smoked Oak Veneer',
    startingPrice: '₹5.80 Lakh',
    features: [
      'Monolithic waterfall travertine island with 4-seater bar',
      'Flush induction hob with silent downdraft exhaust',
      'Motorized touch-to-open Blum titanium drawers',
      'Integrated bar cabinet with ambient warm lighting',
    ],
    quoteDefaults: {
      configuration: '4BHK',
      scope: 'kitchen_only',
      aesthetic: 'luxe_contemporary',
      materialTier: 'bespoke_veneer',
    },
  },
  {
    id: 'tax-k-4',
    category: 'kitchen',
    title: 'Parallel Galley Chef Suite',
    subtitle: 'Dual Countertop High-Efficiency Layout',
    tag: 'Chef Kitchen Layout',
    image: ASSET_LIBRARY.kitchenParallel,
    localAiImage: getAssetUrl('/images/kitchen_parallel_luxury.jpg'),
    recommendedSize: '110 - 160 sq.ft Linear',
    hardwareSpec: 'Hafele Matrix Box Slim / Hettich InnoTech',
    coreMaterial: 'High-Density Moisture-Resistant HDHMR',
    edgeBanding: 'PUR Hot-Melt Waterproof Profile',
    finishType: 'Textured Fluted Oak with Ecru Anti-Glare Laminate',
    startingPrice: '₹3.40 Lakh',
    features: [
      'Separate dry and wet prep counters',
      'Heavy-duty pot drawers with 50kg dynamic load capacity',
      'Recessed magnetic track ceiling lights',
      '100% boiling-water-proof Action TESA HDHMR core',
    ],
    quoteDefaults: {
      configuration: '3BHK',
      scope: 'kitchen_only',
      aesthetic: 'japandi',
      materialTier: 'premium_german',
    },
  },

  // --- BEDROOMS ---
  {
    id: 'tax-b-1',
    category: 'bedroom',
    title: 'Japandi Minimalist Master Suite',
    subtitle: 'Natural Wood Slat Wall & Platform Bed',
    tag: 'Modern Zen Bedroom',
    image: ASSET_LIBRARY.bedroomJapandi,
    localAiImage: ASSET_LIBRARY.bedroomMasterAi,
    recommendedSize: '160 - 240 sq.ft Master Suite',
    hardwareSpec: 'Hafele Silent Sliding Door Gear + Concealed Hinges',
    coreMaterial: 'Calibrated BWP Plywood with Oak Veneer Accents',
    edgeBanding: 'Real Wood Veneer Edgebanding',
    finishType: 'Natural Ash Slat Paneling + Warm Linen Headboard',
    startingPrice: '₹3.80 Lakh',
    features: [
      'Acoustic oak slat feature wall with warm halo backlight',
      'Floor-to-ceiling wardrobes with seamless finger pulls',
      'Floating nightstands with integrated wireless charging',
      'Calibrated moisture-proof plywood with 10-year warranty',
    ],
    quoteDefaults: {
      configuration: '3BHK',
      scope: 'wardrobes_living',
      aesthetic: 'japandi',
      materialTier: 'bespoke_veneer',
    },
  },
  {
    id: 'tax-b-2',
    category: 'bedroom',
    title: 'Walk-In Dressing & Wardrobe Suite',
    subtitle: 'Satin PU Finish with Fluted Glass Shutters',
    tag: 'Luxury Walk-In Wardrobe',
    image: ASSET_LIBRARY.bedroomClassical,
    localAiImage: getAssetUrl('/images/bedroom_classical_wardrobe.jpg'),
    recommendedSize: '180 - 300 sq.ft Master Suite',
    hardwareSpec: 'Hettich Sensys Integrated Dampening + Brass Pulls',
    coreMaterial: 'Action TESA High-Density Fibreboard',
    edgeBanding: 'Laser Seamless Polyurethane Seal',
    finishType: 'Satin Cream PU Lacquer & Knurled Champagne Brass',
    startingPrice: '₹4.60 Lakh',
    features: [
      'Fluted bronze glass doors with automatic warm sensor lights',
      'Center accessory island with velvet jewelry trays',
      'Hydraulic pull-down garment lifters for top rails',
      'Knurled champagne brass handles with anti-tarnish coating',
    ],
    quoteDefaults: {
      configuration: '4BHK',
      scope: 'wardrobes_living',
      aesthetic: 'modern_classical',
      materialTier: 'bespoke_veneer',
    },
  },
  {
    id: 'tax-b-3',
    category: 'bedroom',
    title: 'Smart Fold-Down Bed & Study Pod',
    subtitle: 'Space-Saving Wall Bed for Guest & Study',
    tag: 'Smart Space-Saver',
    image: ASSET_LIBRARY.bedroomSmartPod,
    localAiImage: getAssetUrl('/images/bedroom_smart_pod.jpg'),
    recommendedSize: '110 - 150 sq.ft Guest/Study',
    hardwareSpec: 'Italian Hydraulic Murphy Counterbalance Mechanism',
    coreMaterial: 'BWP Grade Moisture Plywood',
    edgeBanding: 'High-Impact German ABS Edge',
    finishType: 'Warm Ecru Silk Matte Finish with Light Oak Desk',
    startingPrice: '₹2.75 Lakh',
    features: [
      'Finger-touch hydraulic fold-down queen bed',
      'Study desk stays completely level during folding',
      'Built-in bookshelves with reading LED spotlights',
      'Italian hydraulic mechanism tested for 10,000+ folds',
    ],
    quoteDefaults: {
      configuration: '2BHK',
      scope: 'wardrobes_living',
      aesthetic: 'warm_minimalist',
      materialTier: 'premium_german',
    },
  },

  // --- LIVING & DINING ---
  {
    id: 'tax-l-1',
    category: 'living',
    title: 'Monolithic Marble & Acoustic Fluted Lounge',
    subtitle: 'Italian Marble Cladding & Floating Entertainment Unit',
    tag: 'Signature Living Lounge',
    image: ASSET_LIBRARY.livingAcoustic,
    localAiImage: ASSET_LIBRARY.livingLoungeAi,
    recommendedSize: '220 - 350 sq.ft Living Area',
    hardwareSpec: 'Push-to-open heavy-duty floating wall brackets',
    coreMaterial: 'HDHMR Core with Natural Travertine Cladding',
    edgeBanding: 'Hand-Mitered 45-degree Stone Profile',
    finishType: 'Honed Botticino Marble + Smoked Walnut Fluting',
    startingPrice: '₹3.90 Lakh',
    features: [
      'Seamless TV wall with zero visible cables or wires',
      'Acoustic fluted oak backing for crisp home-theater sound',
      'Floating credenza with tinted fluted glass flaps',
      'Italian Botticino marble slab with 10-year warranty',
    ],
    quoteDefaults: {
      configuration: '3BHK',
      scope: 'wardrobes_living',
      aesthetic: 'luxe_contemporary',
      materialTier: 'bespoke_veneer',
    },
  },
  {
    id: 'tax-l-2',
    category: 'living',
    title: 'Travertine Dining & Bar Credenza',
    subtitle: 'Curved Fluted Credenza & 8-Seater Dining Base',
    tag: 'Dining & Bar Suite',
    image: ASSET_LIBRARY.livingTravertine,
    localAiImage: getAssetUrl('/images/living_travertine_dining.jpg'),
    recommendedSize: '150 - 220 sq.ft Dining Area',
    hardwareSpec: 'Blum Tip-On Mechanical Push System',
    coreMaterial: 'Calibrated Plywood & Engineered Travertine',
    edgeBanding: 'Champagne Metal Accent Trim',
    finishType: 'Matte Travertine Stone & Warm Ivory Lacquer',
    startingPrice: '₹3.10 Lakh',
    features: [
      'Curved fluted buffet credenza with stemware glass racks',
      'Backlit natural stone niche with warm dimmer control',
      'Solid fluted dining table plinth seating up to 8',
      'Champagne brass metal inlays with scratch-resistant PVD',
    ],
    quoteDefaults: {
      configuration: '3BHK',
      scope: 'full_turnkey',
      aesthetic: 'warm_minimalist',
      materialTier: 'premium_german',
    },
  },

  // --- COMMERCIAL ---
  {
    id: 'tax-c-1',
    category: 'commercial',
    title: 'Boutique Executive Suite & Boardroom',
    subtitle: 'Acoustic Partitions & Executive Boardroom Joinery',
    tag: 'Commercial Office Suite',
    image: ASSET_LIBRARY.commercialSuite,
    localAiImage: getAssetUrl('/images/commercial_executive_suite.jpg'),
    recommendedSize: '800 - 2500 sq.ft Office',
    hardwareSpec: 'Commercial Grade Heavy Duty Hinges & Access Hardware',
    coreMaterial: 'Commercial Grade Fire-Retardant HDHMR',
    edgeBanding: 'Industrial 2mm Impact Resistant Banding',
    finishType: 'Smoked Oak Paneling with Champagne Metal Inlays',
    startingPrice: '₹8.50 Lakh',
    features: [
      'Sound-dampened double-glazed acoustic glass cabins',
      'Conference table with motorized pop-up power & HDMI ports',
      'Fluted reception desk with backlit company logo wall',
      'Ergonomic storage cabinets with digital security locks',
    ],
    quoteDefaults: {
      configuration: 'Commercial',
      scope: 'full_turnkey',
      aesthetic: 'warm_minimalist',
      materialTier: 'bespoke_veneer',
    },
  },
  {
    id: 'tax-c-2',
    category: 'commercial',
    title: 'High-End Retail Flagship Atelier',
    subtitle: 'Museum-Grade Display Units & Spotlight Niches',
    tag: 'Luxury Retail Atelier',
    image: ASSET_LIBRARY.commercialRetail,
    localAiImage: getAssetUrl('/images/commercial_retail_atelier.jpg'),
    recommendedSize: '600 - 1800 sq.ft Retail Space',
    hardwareSpec: 'Invisible magnetic shelving pins & push locks',
    coreMaterial: 'High-Density Moisture Proof Plywood',
    edgeBanding: 'Seamless CNC Chamfered Profile',
    finishType: 'Warm Alabaster Micro-cement & Satin Brass',
    startingPrice: '₹7.20 Lakh',
    features: [
      'High-CRI 95+ museum spotlights for true product colors',
      'Curved cash counter with solid travertine plinth',
      'Full-height concealed storage behind display walls',
      'Toughened anti-shatter glass display vitrines',
    ],
    quoteDefaults: {
      configuration: 'Commercial',
      scope: 'full_turnkey',
      aesthetic: 'luxe_contemporary',
      materialTier: 'bespoke_veneer',
    },
  },
];

// 2. Canva-Style 5-Step Workflow Milestones
export const WORKFLOW_MILESTONES: WorkflowMilestone[] = [
  {
    stepNumber: '01',
    stepIndex: 1,
    title: '3D Virtual Blueprint & Laser Scan',
    subtitle: 'Precision Measurement & 360° VR Design',
    description:
      'Sub-millimeter laser scan and photorealistic 3D design walkthrough. See your completed home in 3D before factory production starts.',
    keyDeliverable: '3D Virtual Model & Material Palette',
    inspectionStandard: '0.5mm Laser Accuracy',
    badge: 'Zero Guesswork',
    icon: 'Compass',
    highlightStat: '48h Turnaround',
    illustrationImage: ASSET_LIBRARY.blueprintScanAi,
  },
  {
    stepNumber: '02',
    stepIndex: 2,
    title: '100% Price Lock BOQ',
    subtitle: 'Transparent Itemized Quotation',
    description:
      'Every board, hinge, and finish itemized down to the penny. Zero midway price hikes or surprise extras, guaranteed in writing.',
    keyDeliverable: 'Itemized Schedule with Fixed Rate Lock',
    inspectionStandard: 'Zero Hidden Costs Clause',
    badge: '100% Price Lock',
    icon: 'ShieldCheck',
    highlightStat: '100% Price-Locked',
    illustrationImage: ASSET_LIBRARY.draftingDetailAi,
  },
  {
    stepNumber: '03',
    stepIndex: 3,
    title: 'Off-Site German Factory Build',
    subtitle: 'Precision Homag CNC Fabrication',
    description:
      '90% of modular woodwork is cut and edge-banded off-site in our precision factory. Your home stays clean, silent, and dust-free.',
    keyDeliverable: 'PUR Moisture-Sealed Factory Units',
    inspectionStandard: 'German Homag Tolerances',
    badge: 'Dust-Free Home',
    icon: 'Factory',
    highlightStat: '90% Off-Site Build',
    illustrationImage: ASSET_LIBRARY.factoryCncAi,
  },
  {
    stepNumber: '04',
    stepIndex: 4,
    title: '45-Day Guaranteed Handover',
    subtitle: 'Strict On-Time Delivery Guarantee',
    description:
      'Guaranteed 45-day handover from site clearance. If delayed by even a single day, we pay you ₹1,500/day compensation directly.',
    keyDeliverable: 'Turnkey Handover & Clean Inspection',
    inspectionStandard: '₹1,500/Day Delay Penalty',
    badge: 'Guaranteed Timeline',
    icon: 'Clock',
    highlightStat: '45 Days Flat',
    illustrationImage: ASSET_LIBRARY.handoverGiftAi,
  },
  {
    stepNumber: '05',
    stepIndex: 5,
    title: '10-Year Certified Warranty',
    subtitle: 'Bi-Annual Complimentary Tune-ups',
    description:
      '10-year structural warranty certificate backed by Sneha Enterprises, plus free bi-annual technician checkups to service all hinges & drawers.',
    keyDeliverable: '10-Year Warranty Certificate + Service Bond',
    inspectionStandard: 'Sneha Enterprises Certified',
    badge: '10-Year Peace of Mind',
    icon: 'Award',
    highlightStat: '10-Year Bond',
    illustrationImage: ASSET_LIBRARY.materialsMoodboardAi,
  },
];

// 3. Google Reviews & Video Testimonials Data
export const GOOGLE_REVIEWS_DATA: GoogleReviewItem[] = [
  {
    id: 'rev-1',
    author: 'Priya & Rohan Nair',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    location: 'Bangalore, Karnataka',
    isLocalGuide: true,
    reviewsCount: 28,
    rating: 5,
    relativeTime: '2 weeks ago',
    projectBadge: 'Prestige Lakeside Habitat, 3BHK Handover',
    title: 'Delivered in 43 days flat with flawless German edge-banding!',
    content:
      'We had heard horror stories of interior contractors delaying handovers by months. ShineX Infra Interior, backed by Sneha Enterprises, completely shattered that stereotype. Their 100% price lock meant our quote never moved by a single rupee. The fluted ash bedroom and island kitchen look straight out of an Architectural Digest editorial!',
    videoReel: {
      id: 'reel-priya',
      title: "Priya's 45-Day Handover Story",
      triggerLabel: "Watch Priya's 45-Day Handover Video",
      homeownerName: 'Priya & Rohan Nair',
      projectTag: 'Prestige Lakeside 3BHK',
      handoverDays: 43,
      location: 'Bangalore East',
      thumbnail: ASSET_LIBRARY.clientCouple,
      duration: '1:42',
      quote:
        'The precision was unreal. They finished 2 days before the 45-day deadline, and the cleaning team left our apartment spotless.',
      highlights: [
        'Custom Cashmere L-Shaped Kitchen with Blum Tandembox',
        'Floor-to-ceiling PU master bedroom wardrobe with internal sensors',
        'Italian Botticino marble living TV atelier',
      ],
      specs: {
        kitchen: 'Action TESA HDHMR + Blum Soft-Close',
        wardrobes: 'Satin PU Lacquer with Champagne Brass Handles',
        livingWall: 'Acoustic Slats + Hone Botticino Slab',
      },
    },
  },
  {
    id: 'rev-2',
    author: 'Vikram Singhania',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    location: 'Mumbai, Maharashtra',
    isLocalGuide: true,
    reviewsCount: 42,
    rating: 5,
    relativeTime: '3 weeks ago',
    projectBadge: 'Lodha Altamount, 4BHK Duplex Penthouse',
    title: 'The European atelier craftsmanship is unmatched in India.',
    content:
      'As someone who travels between Frankfurt and Mumbai, I wanted true German factory tolerances. ShineX brought in Homag laser edge-banded cabinetry and seamless quartz joints that rival Italian imported kitchens at one-third the cost. Sneha Enterprises managed the structural permissions with effortless professionalism.',
    videoReel: {
      id: 'reel-vikram',
      title: "Vikram's Penthouse Showcase",
      triggerLabel: "Watch Vikram's Penthouse Showcase Video",
      homeownerName: 'Vikram Singhania',
      projectTag: 'Lodha Altamount 4BHK Duplex',
      handoverDays: 44,
      location: 'South Mumbai',
      thumbnail: ASSET_LIBRARY.clientVikram,
      duration: '2:15',
      quote:
        'Zero carpentry dust inside the penthouse. All modular units arrived pre-laminated and boxed from their precision factory.',
      highlights: [
        'Monolithic Travertine Kitchen Island with Downdraft Hob',
        'Smoked European Oak Veneer Wardrobes with Servo-Drive',
        'Concealed Magnetic Track Lighting in False Ceiling',
      ],
      specs: {
        kitchen: 'Travertine Waterfall + Blum Legrabox Pure',
        wardrobes: 'Natural Smoked Oak + Satin Bronze Trim',
        livingWall: 'Bookmatched Italian Botticino Cladding',
      },
    },
  },
  {
    id: 'rev-3',
    author: 'Ananya Deshmukh',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    location: 'Bangalore, Karnataka',
    isLocalGuide: false,
    reviewsCount: 14,
    rating: 5,
    relativeTime: '1 month ago',
    projectBadge: 'Godrej Woodsman Estate, 2BHK Modern Turnkey',
    title: 'Saved ₹2.4 Lakhs with their 15% digital booking grant!',
    content:
      'We used their 6-step online cost calculator and booked our site consultation with the 15% discount voucher. The resulting BOQ was down-to-the-penny accurate. Their project manager kept us updated via daily photo logs. Their 10-year warranty gives my family total peace of mind.',
    videoReel: {
      id: 'reel-ananya',
      title: "Ananya's 2BHK Transformation Tour",
      triggerLabel: "Watch Ananya's 2BHK Transformation Video",
      homeownerName: 'Ananya Deshmukh',
      projectTag: 'Godrej Woods 2BHK',
      handoverDays: 41,
      location: 'Hebbal, Bangalore',
      thumbnail: ASSET_LIBRARY.clientPriya,
      duration: '1:18',
      quote:
        'They turned a gloomy builder-finish apartment into a sun-drenched warm alabaster sanctuary.',
      highlights: [
        'Smart Murphy fold-down guest bed with study desk',
        'U-shaped champagne acrylic kitchen suite',
        'Minimalist fluted entryway shoe atelier',
      ],
      specs: {
        kitchen: 'Acrylic Anti-Scratch + Hettich InnoTech',
        wardrobes: 'Warm Cream Silk Matte Finish',
        livingWall: 'Perimeter Cove 2700K Architectural Lighting',
      },
    },
  },
  {
    id: 'rev-4',
    author: 'Rahul & Divya Mehra',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    location: 'Bangalore, Karnataka',
    isLocalGuide: true,
    reviewsCount: 19,
    rating: 5,
    relativeTime: '1 month ago',
    projectBadge: 'Embassy Boulevard, Private Turnkey Villa',
    title: 'Turnkey architectural perfection for our 4,200 sq.ft villa.',
    content:
      'Managing a large villa project from overseas seemed daunting until we partnered with ShineX. From laser 3D scanning to civil plumbing reconfiguration, Sneha Enterprises took complete responsibility. The penalty clause gave us great confidence, but they finished 5 days early!',
  },
  {
    id: 'rev-5',
    author: 'Dr. Siddharth & Neha Verma',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
    location: 'Mumbai, Maharashtra',
    isLocalGuide: false,
    reviewsCount: 8,
    rating: 5,
    relativeTime: '2 months ago',
    projectBadge: 'Brigade Exotica, 3BHK Japandi Sanctuary',
    title: 'The wabi-sabi tactile warmth is deeply soothing.',
    content:
      'We specifically asked for no generic high-gloss laminates or harsh clinical white lighting. The design team curated warm limestone, acoustic timber slats, and 2700K cove lighting that feels like a Kyoto luxury retreat. Exceptional attention to detail.',
  },
];

// Factory and Legal Profile Data
export const BRAND_PROFILE = {
  brandName: 'ShineX Infra Interior',
  parentEntity: 'Sneha Enterprises',
  gstRegistered: '29ABCDE1234F1Z5',
  supportPhone: '+91 98450 12890',
  supportEmail: 'concierge@shinexinfra.com',
  whatsappDirect: 'https://wa.me/919845012890?text=Hi%20ShineX%20Team%2C%20I%20am%20interested%20in%20a%20turnkey%20interior%20consultation.',
  experienceCenters: [
    {
      city: 'Bangalore Atelier',
      address: 'Level 3, Indiranagar 100ft Road, Defence Colony, Bengaluru, Karnataka 560038',
      hours: 'Mon - Sun: 10:00 AM - 8:30 PM',
      phone: '+91 98450 12890',
    },
    {
      city: 'Mumbai Atelier',
      address: 'Signature Tower, Off BKC Main Road, Bandra East, Mumbai, Maharashtra 400051',
      hours: 'Mon - Sun: 10:00 AM - 8:30 PM',
      phone: '+91 98200 45678',
    },
  ],
  factories: [
    {
      name: 'Bengaluru Precision Milling Works',
      location: 'Plot 48, Jigani Industrial Area Phase II, Bengaluru',
      machinery: 'Homag Germany CNC Laser Edge-Banding & Biesse Rover Milling',
    },
    {
      name: 'Mumbai Turnkey Fabrication Hub',
      location: 'Unit 12, Logistic Industrial Park, Bhiwandi-Thane Corridor',
      machinery: 'German Hot-Melt PUR Automated Panel Processing',
    },
  ],
};

// 5-Room Architectural Before & After Parallax Transformation Gallery
export const BEFORE_AFTER_GALLERY: BeforeAfterItem[] = [
  {
    id: 'ba-living',
    category: 'Living Lounge & Dining',
    title: 'Grand Travertine Penthouse Lounge',
    subtitle: 'From Raw Concrete to Luxury Italian Marble Penthouse in 38 Days',
    beforeImage: getAssetUrl('/images/before_construction_shell.jpg'),
    afterImage: getAssetUrl('/images/hero_luxury_bg.jpg'),
    beforeLabel: 'Raw Concrete Site',
    afterLabel: '38-Day Turnkey Handover',
    sqft: '480 sq.ft Living & Dining',
    handoverDays: 38,
    specs: {
      coreMaterial: 'Italian Botticino Marble + Natural Oak',
      hardware: 'Concealed Magnetic Track Lights',
      lighting: 'Warm Ambient Lighting (2700K)',
      warranty: '10-Year Sneha Enterprises Guarantee',
    },
    highlightQuote: '“Transformed our bare dusty flat into a luxury home in just 38 days.” — Dr. Alok & Priya',
  },
  {
    id: 'ba-kitchen',
    category: 'Chef Modular Kitchen',
    title: 'Monolithic Travertine & Calacatta Island',
    subtitle: 'From Dangling Pipes to Modern Island Kitchen in 26 Days',
    beforeImage: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1600&q=80',
    afterImage: getAssetUrl('/images/luxury_kitchen_island.jpg'),
    beforeLabel: 'Rough Screed & Brickwork',
    afterLabel: '26-Day Factory Handover',
    sqft: '210 sq.ft Open Culinary Studio',
    handoverDays: 26,
    specs: {
      coreMaterial: 'Action TESA BWP HDHMR + Natural Travertine',
      hardware: 'Blum Soft-Close Motorized Drawers',
      lighting: 'Warm Champagne Profile LEDs',
      warranty: '10-Year Water & Termite Guarantee',
    },
    highlightQuote: '“The motorized drawers and travertine island feel like a 5-star hotel.” — Vikram & Sunita',
  },
  {
    id: 'ba-master-suite',
    category: 'Master Bedroom Suite',
    title: 'Acoustic Japandi Minimalist Sanctuary',
    subtitle: 'From Bare Brickwork to Japandi Master Suite in 31 Days',
    beforeImage: 'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f7?auto=format&fit=crop&w=1600&q=80',
    afterImage: getAssetUrl('/images/luxury_master_suite.jpg'),
    beforeLabel: 'Hollow Block Masonry',
    afterLabel: '31-Day Finished Suite',
    sqft: '280 sq.ft Master Bed & Study',
    handoverDays: 31,
    specs: {
      coreMaterial: 'Natural White Oak + Sound-Dampening Slats',
      hardware: 'Concealed Touch-Latch Hardware',
      lighting: 'Indirect Headboard Halo Glow',
      warranty: '10-Year Sneha Enterprises Guarantee',
    },
    highlightQuote: '“Zero carpenter dust on site. Handed over on schedule with top-class finish.” — Rohan M.',
  },
  {
    id: 'ba-wardrobe',
    category: 'Walk-In Dressing Suite',
    title: 'Haute Couture Fluted Glass Dressing Atelier',
    subtitle: 'From Dark Alcove to Glass Walk-In Wardrobe in 22 Days',
    beforeImage: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=1600&q=80',
    afterImage: getAssetUrl('/images/bedroom_classical_wardrobe.jpg'),
    beforeLabel: 'Rough Plaster Niche',
    afterLabel: '22-Day Walk-In Dressing',
    sqft: '160 sq.ft Dressing Chamber',
    handoverDays: 22,
    specs: {
      coreMaterial: 'High-Density Ply + Fluted Tempered Glass',
      hardware: 'Hafele Heavy-Duty Concealed Pivots',
      lighting: 'Automatic Sensor Warm Lights',
      warranty: '10-Year Hardware Alignment Guarantee',
    },
    highlightQuote: '“Every wardrobe light turns on automatically when opened. True luxury.” — Meera & Ananya',
  },
  {
    id: 'ba-studio',
    category: 'Executive Studio & Office',
    title: 'Smoked Walnut Executive Study & Library',
    subtitle: 'From Bare Concrete to Executive Office Studio in 24 Days',
    beforeImage: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=1600&q=80',
    afterImage: getAssetUrl('/images/commercial_executive_suite.jpg'),
    beforeLabel: 'Exposed Electrical Chases',
    afterLabel: '24-Day Finished Studio',
    sqft: '190 sq.ft Creative Executive Studio',
    handoverDays: 24,
    specs: {
      coreMaterial: 'Smoked Walnut Wood + Brass Trim',
      hardware: 'Concealed Wire Chases & Soft-Close',
      lighting: 'Glare-Free Architectural Task Lighting',
      warranty: '10-Year Structural Guarantee',
    },
    highlightQuote: '“Delivered 4 days ahead of schedule. Flawless German woodwork.” — Sanjay K.',
  },
];

